name: Trigger auto deployment for settings-api-git-ms

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - "nodejs-microservices/packages/settings-api/**"
    - '.github/workflows/settings-api-git-ms-AutoDeployTrigger-cc26807c-dfa5-4e72-b272-0948895aaf4d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SETTINGSAPIGITMS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SETTINGSAPIGITMS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SETTINGSAPIGITMS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/nodejs-microservices
          dockerfilePath: packages/settings-api/Dockerfile
          registryUrl: rejestrkontenerow.azurecr.io 
          registryUsername: ${{ secrets.GATEWAYAPIGITMS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GATEWAYAPIGITMS_REGISTRY_PASSWORD }}
          containerAppName: settings-api-git-ms
          resourceGroup: aws-szkolenie-MS
          imageToBuild: rejestrkontenerow.azurecr.io/gateway-api-git-ms:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


